name: locare
description: MVP offline-first de gestão de casas e aluguéis.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Navegação
  go_router: ^14.2.0

  # Estado
  flutter_riverpod: ^2.5.1

  # Validação
  formz: ^0.6.1

  # Backend
  supabase_flutter: ^2.5.0
  
  # Utilitários
  http: ^1.6.0
  logging: ^1.3.0
  mask_text_input_formatter: ^2.9.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
